### ISSUE TITLE
 adb.exe not found

### ISSUE THREAD

**Issue by Dice17** [AdriaGual/marvel-snap-bot#103]
![marvel snap bot](https://user-images.githubusercontent.com/126554274/221828650-f74d682f-26c8-443d-ad13-e337fba9cdf3.png)

I know someone has already ask the same question but i still don't understand it 

How can i fix this issue?

**Comment by paperc07** [comment]
#74

**Comment by Dice17** [comment]
> #74

i follow all the steps there and it ended up like this

**Comment by paperc07** [comment]
ok ok so check out all this one then cause this guy and me where going back and forth until he finally got it hold on let me find it 

#93

**Comment by paperc07** [comment]
If you could please report what you did when you fix it so I can put it in the list of problems

**Comment by Dice17** [comment]
ok will do, btw this doesn't show when i first execute the command, it only show after i execute it the second time

**Comment by paperc07** [comment]
did you sort it out?

**Comment by Dice17** [comment]
it still show the same error

**Comment by Dice17** [comment]
may i know where can i change the port?

**Comment by Dice17** [comment]
$ python start.py
Connection result: already connected to 127.0.0.1:12841

Traceback (most recent call last):
  File "C:\Users\hongz\Desktop\marvel-snap-bot-master\start.py", line 42, in <module>
    player_turn = turn.get_turn(screenshot, screenshot_dimensions, False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hongz\Desktop\marvel-snap-bot-master\turn.py", line 23, in get_turn
    searched_turn = global_utils.search(
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hongz\Desktop\marvel-snap-bot-master\utils\global_utils.py", line 22, in search
    result = cv2.matchTemplate(haystack_image, screenshot, method)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1175: error: (-215:Assertion failed) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function 'cv::matchTemplate'
 
this is the issue now

**Comment by Dice17** [comment]
nevermind it already works thank you so much!!!!

**Comment by Dice17** [comment]
So the first issue is my adb is not install properly so i need to add it to the PATH in environment variables. 
Secondly, my port in bluestacks is not 5555 so i need to change it manually in android connection.py and global utils.py. 
Thirdly, my "pip install opencv-contrib-python" is outdated so the bot just works after i update it.

So these are the issue i encountered, hope this helps!
