### ISSUE TITLE
Discard deck trouble

### ISSUE THREAD

**Issue by human-tetris** [AdriaGual/marvel-snap-bot#44]
I tried to play new deck by looking at available images of cards in bot. Sometimes it stops with this error or `KeyError:'wolverine'`.

```
Traceback (most recent call last):
  File "C:\Users\ASUS\marvel-snap-bot\start.py", line 69, in <module>
    last_move = hand_cards.play_cards(play_info, last_move)
  File "C:\Users\ASUS\marvel-snap-bot\hand_cards.py", line 95, in play_cards
    play_to_make = cp_calc.calc_play(play_info)
  File "C:\Users\ASUS\marvel-snap-bot\cp_calc.py", line 46, in calc_play
    if cp_list.cps[hand_card[0]]['average_cp'] > max_cp_play and cp_list.cps[hand_card[0]]['mana'] <= play_info['mana']:
KeyError: 'swarm'
```

**Comment by AdriaGual** [comment]
The error says that it doesn't find the  `cp_list.cps['swarm']['average_cp']`, check the cp_list.py file

**Comment by human-tetris** [comment]
got it
