### ISSUE TITLE
OSError: [WinError 123] Turn Images

### ISSUE THREAD

**Issue by jcalloway** [AdriaGual/marvel-snap-bot#48]
Traceback (most recent call last):
  File "start.py", line 42, in <module>
    player_turn = turn.get_turn(screenshot, screenshot_dimensions, False)
  File "C:\Users\James\marvel-snap-bot\turn.py", line 21, in get_turn
    for turn_haystack in os.listdir(config.turns_folder):
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'images_folder + C:\\Users\\James\\marvel-snap-bot\\images\\turns'

Any advice is appreciated.

**Comment by jcalloway** [comment]
Fixed the paths in the config and the bot started.
