### ISSUE TITLE
KeyError in cp_calc.py

### ISSUE THREAD

**Issue by PeanutJar-Jelly** [AdriaGual/marvel-snap-bot#5]
I noticed that the bot will crash if it hits the location new_york, reproduced multiple times.  It appears the issue is there is no new_york field_name in field_list.py

Traceback (most recent call last):
  File "C:\Users\*\marvel-snap-bot\start.py", line 71, in <module>
    last_move = hand_cards.play_cards(play_info, last_move)
  File "C:\Users\*\marvel-snap-bot\hand_cards.py", line 82, in play_cards
    play_to_make = cp_calc.calc_play(play_info)
  File "C:\Users\*\marvel-snap-bot\cp_calc.py", line 73, in calc_play
    if field_list.list[field_name]['min_play'] == 1:
KeyError: 'new_york'

**Comment by AdriaGual** [comment]
True! I've now added it, you can pull the repository!

If you see anything similar, you can create a PR and I'll review it!

Have a great day!
