### ISSUE TITLE
ValueError: needle dimension(s) exceed the haystack image or region dimensions

### ISSUE THREAD

**Issue by HolidayPhenom** [AdriaGual/marvel-snap-bot#70]
$ python start.py
Connection result: already connected to 127.0.0.1:5555

[get_turn] Time elapsed: 0:00:00.038124
---------------------------
Picture: 0
* Turn: 3
[get_mana] Time elapsed: 0:00:00.036783
* Mana: 3
Traceback (most recent call last):
  File "C:\Users\User\marvel-snap-bot\start.py", line 65, in <module>
    play_info = info.get_info(
  File "C:\Users\User\marvel-snap-bot\info.py", line 28, in get_info
    my_hand_cards = hand_cards.get_my_hand_cards(screenshot, screenshot_dimensions, counter, True)
  File "C:\Users\User\marvel-snap-bot\hand_cards.py", line 25, in get_my_hand_cards
    card_location = pyautogui.locate(
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyautogui\__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\pyautogui\__init__.py", line 189, in locate
    return pyscreeze.locate(*args, **kwargs)
  File "C:\python39\lib\site-packages\pyscreeze\__init__.py", line 353, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
  File "C:\python39\lib\site-packages\pyscreeze\__init__.py", line 219, in _locateAll_opencv
    raise ValueError('needle dimension(s) exceed the haystack image or region dimensions')
ValueError: needle dimension(s) exceed the haystack image or region dimensions

**Comment by AdriaGual** [comment]
```
pip install opencv-python==4.7.0.68
pip install opencv-python-headless==4.6.0.66
pip install numpy==1.21.0
```

**Comment by HolidayPhenom** [comment]
After: 
pip install opencv-python==4.7.0.68
pip install opencv-python-headless==4.6.0.66
pip install numpy==1.21.0


Followed with:

$ python start.py
Connection result: already connected to 127.0.0.1:5555

[get_turn] Time elapsed: 0:00:00.038042
[get_turn] Time elapsed: 0:00:00.038687
[get_turn] Time elapsed: 0:00:00.039157
[get_turn] Time elapsed: 0:00:00.040205
[get_turn] Time elapsed: 0:00:00.037203
[get_turn] Time elapsed: 0:00:00.038304
[get_turn] Time elapsed: 0:00:00.037009
[get_turn] Time elapsed: 0:00:00.037075
[get_turn] Time elapsed: 0:00:00.036588
[get_turn] Time elapsed: 0:00:00.036939
[get_turn] Time elapsed: 0:00:00.036942
[get_turn] Time elapsed: 0:00:00.036409
[get_turn] Time elapsed: 0:00:00.036783
[get_turn] Time elapsed: 0:00:00.035803
[get_turn] Time elapsed: 0:00:00.036510
[get_turn] Time elapsed: 0:00:00.033663
[get_turn] Time elapsed: 0:00:00.033946
[get_turn] Time elapsed: 0:00:00.034644
[get_turn] Time elapsed: 0:00:00.033651
[get_turn] Time elapsed: 0:00:00.035609
[get_turn] Time elapsed: 0:00:00.034645
[get_turn] Time elapsed: 0:00:00.035728
---------------------------
Picture: 0
* Turn: 2
[get_mana] Time elapsed: 0:00:00.006908
* Mana: 2
Traceback (most recent call last):
  File "C:\Users\User\marvel-snap-bot\start.py", line 65, in <module>
    play_info = info.get_info(
  File "C:\Users\User\marvel-snap-bot\info.py", line 28, in get_info
    my_hand_cards = hand_cards.get_my_hand_cards(screenshot, screenshot_dimensions, counter, False)
  File "C:\Users\User\marvel-snap-bot\hand_cards.py", line 25, in get_my_hand_cards
    card_location = pyautogui.locate(
  File "C:\python39\lib\site-packages\pyautogui\__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
  File "C:\python39\lib\site-packages\pyautogui\__init__.py", line 189, in locate
    return pyscreeze.locate(*args, **kwargs)
  File "C:\python39\lib\site-packages\pyscreeze\__init__.py", line 353, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
  File "C:\python39\lib\site-packages\pyscreeze\__init__.py", line 219, in _locateAll_opencv
    raise ValueError('needle dimension(s) exceed the haystack image or region dimensions')
ValueError: needle dimension(s) exceed the haystack image or region dimensions

**Comment by HolidayPhenom** [comment]
$ pip install pyautogui --user
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\user\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\user\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python39\lib\site-packages)
Requirement already satisfied: pyautogui in c:\python39\lib\site-packages (0.9.53)
Requirement already satisfied: pymsgbox in c:\python39\lib\site-packages (from pyautogui) (1.0.9)
Requirement already satisfied: PyTweening>=1.0.1 in c:\python39\lib\site-packages (from pyautogui) (1.0.4)
Requirement already satisfied: pyscreeze>=0.1.21 in c:\python39\lib\site-packages (from pyautogui) (0.1.28)
Requirement already satisfied: pygetwindow>=0.0.5 in c:\python39\lib\site-packages (from pyautogui) (0.0.9)
Requirement already satisfied: mouseinfo in c:\python39\lib\site-packages (from pyautogui) (0.1.3)
Requirement already satisfied: pyrect in c:\python39\lib\site-packages (from pygetwindow>=0.0.5->pyautogui) (0.2.0)
Requirement already satisfied: pyperclip in c:\python39\lib\site-packages (from mouseinfo->pyautogui) (1.8.2)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\user\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\user\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\user\appdata\roaming\python\python39\site-packages)
WARNING: Ignoring invalid distribution -pencv-python-headless (c:\users\user\appdata\roaming\python\python39\site-packages)

**Comment by HolidayPhenom** [comment]
***SOLVED*** 
The dimensions of pictures I was importing into the data folder for card folders were not the right dimensions.
