### ISSUE TITLE
OpenCV Issue

### ISSUE THREAD

**Issue by KSteez11** [AdriaGual/marvel-snap-bot#72]
Ill attach a screenshot with some errors ive received. Someone else had the same error as me, but the fix did not help me for some odd reason.
<img width="448" alt="Screenshot 2023-02-10 173404" src="https://user-images.githubusercontent.com/124807247/218221862-b7e920b5-f069-49a8-a06e-e131d6bd617c.png">

**Comment by AdriaGual** [comment]
Check that you have the numpy version `numpy==1.21.0`

**Comment by terrycwc1124** [comment]
i resolved by 

pip uninstall opencv-python-headless -y 

pip install opencv-python --upgrade

**Comment by HolidayPhenom** [comment]
$ python start.py
Traceback (most recent call last):
  File "C:\Users\User\marvel-snap-bot\start.py", line 3, in <module>
    import info
  File "C:\Users\User\marvel-snap-bot\info.py", line 4, in <module>
    import hand_cards
  File "C:\Users\User\marvel-snap-bot\hand_cards.py", line 9, in <module>
    import pyautogui
  File "C:\python39\lib\site-packages\pyautogui\__init__.py", line 183, in <module>
    import pyscreeze
  File "C:\python39\lib\site-packages\pyscreeze\__init__.py", line 47, in <module>
    RUNNING_CV_2 = cv2.__version__[0] < '3'
AttributeError: module 'cv2' has no attribute '__version__'

**Comment by HolidayPhenom** [comment]
$ python start.py
Connection result: already connected to 127.0.0.1:5555

---------------------------
Picture: 0
* Turn: -2
[get_mana] Time elapsed: 0:00:00.004660
* Mana: 0
[get_my_hand_cards] Time elapsed: 0:00:02.695228
Hand_cards:
elektra
okoye
squirrel_girl
[get_fields] Time elapsed: 0:00:00.832506
* Active fields:
['first_field: strange_academy', 'second_field: monster_island', 'third_field: next_2_turns']
[get_player_fields_cards] Time elapsed: 0:00:00.001983
* Player field cards:
---------------------------
| |-|-| || |x|-| || |-|-| |
| |-|-| || |-|-| || |-|-| |
---------------------------
Traceback (most recent call last):
  File "C:\Users\User\code\marvel-snap-bot\start.py", line 65, in <module>
    play_info = info.get_info(
  File "C:\Users\User\code\marvel-snap-bot\info.py", line 41, in get_info
    cv2.waitKey(10)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1333: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvWaitKey'

**Comment by AdriaGual** [comment]
pip install opencv-python==4.7.0.68
pip install opencv-python-headless==4.6.0.66

**Comment by eimia-q** [comment]
> Check that you have the numpy version `numpy==1.21.0`

Does it have to be the exact version? I have 1.24.2 and can't seem to downgrade

> pip install opencv-python==4.7.0.68 
> pip install opencv-python-headless==4.6.0.66

These are correct

**Comment by AdriaGual** [comment]
Exact versions, always.

Just uninstalll the 1.24.2 and install the 1.21.0

**Comment by eimia-q** [comment]
> Exact versions, always.
> 
> Just uninstalll the 1.24.2 and install the 1.21.0

Thanks for the reply. I've finally gotten numpy on 1.21.0 and am still getting the same error. Have tried all fixes in this thread.

[get_fields] Time elapsed: 0:00:01.029457
* Active fields:
['first_field: washington_dc', 'second_field: next_turn', 'third_field: next_2_turns']
[get_player_fields_cards] Time elapsed: 0:00:00.002736
* Player field cards:
---------------------------
| |-|-| || |-|-| || |-|-| |
| |-|-| || |-|-| || |-|-| |
---------------------------
Traceback (most recent call last):
  File "start.py", line 65, in <module>
    play_info = info.get_info(
  File "C:\Users\Jake\marvel-snap-bot\info.py", line 41, in get_info
    cv2.waitKey(10)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1333: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvWaitKey'

**Comment by eimia-q** [comment]
FIXED WITH pip install opencv-contrib-python

**Comment by nixtynine** [comment]
sirni@NIX MINGW64 /c/marvel-snap-bot (master)
$ python start.py
Traceback (most recent call last):
  File "C:\marvel-snap-bot\start.py", line 1, in <module>
    from utils import android_connection, global_utils
  File "C:\marvel-snap-bot\utils\android_connection.py", line 4, in <module>
    import config
  File "C:\marvel-snap-bot\config.py", line 1
    adb_path = r"C:\Users\paper\marvel-snap-bot\platform-tools
               ^
SyntaxError: unterminated string literal (detected at line 1)


how to fix this error

**Comment by paperc07** [comment]
@nixtynine #74
