### ISSUE TITLE
SyntaxError: '{' was never closed

### ISSUE THREAD

**Issue by HolidayPhenom** [AdriaGual/marvel-snap-bot#78]
$ python start.py
Traceback (most recent call last):
  File "C:\Users\tyler\marvel-snap-bot\start.py", line 3, in <module>
    import info
  File "C:\Users\tyler\marvel-snap-bot\info.py", line 4, in <module>
    import hand_cards
  File "C:\Users\tyler\marvel-snap-bot\hand_cards.py", line 7, in <module>
    import cp_calc
  File "C:\Users\tyler\marvel-snap-bot\cp_calc.py", line 1, in <module>
    import cp_list
  File "C:\Users\tyler\marvel-snap-bot\cp_list.py", line 6
    cps = {
          ^
SyntaxError: '{' was never closed

I'm assuming a simple fix but I don't code, so....

**Comment by AdriaGual** [comment]
Maybe you have changed the cp_list file, just get the cp_list from the repo  (i know there has been a PR that adds every card, but maybe it can have some errors, just use the prepared one for now).
